/**
 * The most recent post on senthurayyappan.com.
 *
 * The README names it in a sentence, and that sentence has to be right without anyone
 * remembering to come back and edit it. The site already publishes an RSS feed with
 * its posts newest-first, so this reads the first item rather than duplicating the
 * blog's own ordering rule here.
 *
 * Deliberately not a full XML parser. The feed is generated by app/rss/route.ts in the
 * site's own repository -- one shape, escaped by a function ten lines above the one
 * that emits it -- so a regex over the first <item> is the whole job, and a dependency
 * for it would be a dependency to keep patched forever.
 */

const FEED_URL = 'https://senthurayyappan.com/rss'

const ENTITIES = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&apos;': "'",
}

function unescapeXml(value) {
  return value.replace(/&(amp|lt|gt|quot|apos);/g, (match) => ENTITIES[match])
}

function tag(source, name) {
  const match = source.match(new RegExp(`<${name}>([\\s\\S]*?)</${name}>`))
  return match ? unescapeXml(match[1].trim()) : null
}

/** `{ title, url }` for the newest post, or null if the feed cannot be read. */
async function latestPost(feedUrl = FEED_URL, warn = console.warn) {
  try {
    const res = await fetch(feedUrl, {
      headers: { 'user-agent': 'senthurayyappan-profile-stats' },
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const xml = await res.text()
    const item = xml.match(/<item>([\s\S]*?)<\/item>/)
    if (!item) throw new Error('no <item> in the feed')
    const title = tag(item[1], 'title')
    const url = tag(item[1], 'link')
    if (!title || !url) throw new Error('an item without a title or a link')
    return { title, url }
  } catch (err) {
    // The board is what this run exists to draw. A blog sentence that is a few days
    // stale is a better outcome than a failed workflow and no redraw at all.
    warn(`could not read ${feedUrl} (${err.message}); leaving the blog line as it is`)
    return null
  }
}

module.exports = { latestPost, FEED_URL }
